# see https://docs.searxng.org/admin/engines/settings.html#use-default-settings
use_default_settings: true
server:
  # base_url is defined in the SEARXNG_BASE_URL environment variable, see .env and docker-compose.yml
  secret_key: "1eca39eb6990154f0cff06202b97e6bff05184c00e2c273fb99828ea4834e49b"  # change this!
  limiter: true  # can be disabled for a private instance
  image_proxy: true
  method: "GET"
ui:
  static_use_hash: true
redis:
  url: redis://redis:6379/0
general:
  debug: false
  instance_name:  "Closed Eyes"
  privacypolicy_url: false
  donation_url: false
  contact_url: false
  enable_metrics: true
search:
  autocomplete: "duckduckgo"
  safe_search: 0
